import { state, saveState, normalizeOneOffEvent, normalizeFixedSchedule, normalizeTask } from './state.js';
import { $, debounce, getFormValue } from './utils.js';
import { addDays, formatDateInput, formatTimeOnly, isSelectedDateToday, isValidTimeRange, roundToFiveMinutes } from './time.js';
import { renderAll, renderCurrentState, renderAutoPlan, updateStateNote, loadConditionInputsForDate } from './render.js';
import { loadGoogleEventsForDate, hasValidGoogleToken, updateGoogleEventFromLocal, createGoogleEventFromLocal, syncLocalEventToGoogle, syncUpdatedLocalEventToGoogle, deleteLocalEvent, deleteGoogleEventById, onSaveGoogleConfig, onClearGoogleConfig, onConnectGoogle, onDisconnectGoogle, loadGoogleEventsForSelectedDate, importGoogleEventsToLocal } from './google-calendar.js';
import { generatePrompt, copyPrompt } from './prompt.js';
import { parseQuickAddInput } from './quick-add.js';
import { showToast, confirmDialog } from './ui-feedback.js';
export function setToday(){ const today=formatDateInput(new Date()); $('selectedDate').value=today; loadConditionInputsForDate(today); const eventDateInput=document.querySelector("#eventForm input[name='date']"); if(eventDateInput) eventDateInput.value=today; hydrateSettingsInputs(); }
function setPanelOpen(panelId,isOpen){ const panel=$(panelId); if(panel) panel.open=isOpen; }
function focusFormPanel(panelId,form,focusSelector='input, select, textarea'){ setPanelOpen('appSettingsPanel',true); const toolsPanel=$('assistToolsPanel'); if(toolsPanel && panelId!=='googleSettingsPanel' && panelId!=='promptAssistSection') toolsPanel.open=false; setPanelOpen(panelId,true); requestAnimationFrame(()=>{ form.scrollIntoView({behavior:'smooth',block:'center'}); form.querySelector(focusSelector)?.focus(); }); }
function closeStateUpdateMenu(){ const menu=$('stateUpdateMenu'); if(menu) menu.open=false; }
export function bindEvents(){ const debouncedSaveCurrentConditionInputs=debounce(saveCurrentConditionInputs,400); $('fixedForm').addEventListener('submit',onSubmitFixedSchedule); $('eventForm').addEventListener('submit',onSubmitOneOffEvent); $('taskForm').addEventListener('submit',onSubmitTask); $('fixedCancelBtn').addEventListener('click',resetFixedForm); $('eventCancelBtn').addEventListener('click',resetEventForm); $('taskCancelBtn').addEventListener('click',resetTaskForm); $('selectedDate').addEventListener('change',onDateChanged); $('sleepHours').addEventListener('input',debouncedSaveCurrentConditionInputs); $('fatigue').addEventListener('input',debouncedSaveCurrentConditionInputs); $('conditionNote').addEventListener('input',debouncedSaveCurrentConditionInputs); $('plannerMode').addEventListener('change',onPlannerModeChanged); $('focusMinutesTarget').addEventListener('input',saveSettingsInputs); $('bufferMinutes').addEventListener('input',saveSettingsInputs); $('fatigueDownBtn').addEventListener('click',()=>{ adjustFatigue(-1); closeStateUpdateMenu(); }); $('fatigueUpBtn').addEventListener('click',()=>{ adjustFatigue(1); closeStateUpdateMenu(); }); $('unexpected30Btn').addEventListener('click',()=>{ addUnexpectedThirtyMinutes(); closeStateUpdateMenu(); }); $('forceReplanBtn').addEventListener('click',()=>{ setPlannerMode('replan'); closeStateUpdateMenu(); }); $('endDayBtn').addEventListener('click',()=>{ setPlannerMode('night'); closeStateUpdateMenu(); }); $('generateBtn').addEventListener('click',generatePrompt); $('copyBtn').addEventListener('click',copyPrompt); $('quickAddBtn')?.addEventListener('click',handleQuickAdd); $('quickAddInput')?.addEventListener('keydown',(e)=>{ if(e.key==='Enter'){ e.preventDefault(); handleQuickAdd(); } }); document.querySelectorAll('[data-quick-example]').forEach((button)=>{ button.addEventListener('click',()=>{ const value=button.getAttribute('data-quick-example')||''; if($('quickAddInput')) $('quickAddInput').value=value; $('quickAddInput')?.focus(); }); }); $('exportBtn').addEventListener('click',exportData); $('importInput').addEventListener('change',importData); $('saveGoogleConfigBtn').addEventListener('click',onSaveGoogleConfig); $('clearGoogleConfigBtn').addEventListener('click',onClearGoogleConfig); $('connectGoogleBtn').addEventListener('click',onConnectGoogle); $('disconnectGoogleBtn').addEventListener('click',onDisconnectGoogle); $('reloadGoogleEventsBtn').addEventListener('click',async()=>{ await loadGoogleEventsForSelectedDate(); }); $('importGoogleToLocalBtn')?.addEventListener('click',()=>{ importGoogleEventsToLocal($('selectedDate')?.value||''); }); $('eventAllDay').addEventListener('change',toggleEventTimeInputs); }
export function hydrateSettingsInputs(){ if($('focusMinutesTarget')) $('focusMinutesTarget').value=String(state.settings?.focusMinutesTarget??180); if($('bufferMinutes')) $('bufferMinutes').value=String(state.settings?.bufferMinutes??10); }
export function saveSettingsInputs(){ state.settings.focusMinutesTarget=Math.max(0,Number($('focusMinutesTarget')?.value||0)); state.settings.bufferMinutes=Math.max(0,Number($('bufferMinutes')?.value||0)); saveState(); renderCurrentState(); renderAutoPlan(); }
export async function onDateChanged(){ const date=$('selectedDate').value; loadConditionInputsForDate(date); const eventDateInput=document.querySelector("#eventForm input[name='date']"); if(eventDateInput && !getFormValue('eventForm','editId')) eventDateInput.value=date; if(hasValidGoogleToken()) await loadGoogleEventsForDate(date,{silent:true}); renderAll(); }
export function saveCurrentConditionInputs(){ const date=$('selectedDate').value; if(!date) return; state.dayConditions[date]={ sleepHours:$('sleepHours').value, fatigue:$('fatigue').value, note:$('conditionNote').value.trim() }; saveState(); renderCurrentState(); renderAutoPlan(); }
export function adjustFatigue(delta){ const current=Number($('fatigue').value||0); const next=Math.max(0,Math.min(10,current+delta)); $('fatigue').value=String(next); saveCurrentConditionInputs(); if(delta<0) updateStateNote('体力を下げたので、重いタスクの優先度を少し落として再設計します。'); else updateStateNote('体力を更新しました。実行案を再計算します。'); showToast(`体力を ${next} に更新しました。`,{variant:'ok',duration:1800}); }
export function addUnexpectedThirtyMinutes(){ if(!isSelectedDateToday($('selectedDate').value)){ showToast('ワンタップの想定外30分は、対象日が今日のときだけ使えます。',{variant:'warn'}); return; } const rounded=roundToFiveMinutes(new Date()); const end=new Date(rounded.getTime()+30*60*1000); state.oneOffEvents.push(normalizeOneOffEvent({ id:crypto.randomUUID(), title:'想定外対応', date:formatDateInput(rounded), start:formatTimeOnly(rounded), end:formatTimeOnly(end), note:'ワンタップ報告 / 自動追加', allDay:false, googleSyncStatus:'local' })); saveState(); updateStateNote('想定外30分を追加したので、残り時間を基準に再設計します。'); renderAll(); showToast('想定外30分を追加しました。',{variant:'ok',duration:2200}); }
export function setPlannerMode(mode){ state.uiState.plannerMode=mode; saveState(); $('plannerMode').value=mode; renderCurrentState(); renderAutoPlan(); generatePrompt(); }
export function onPlannerModeChanged(){ state.uiState.plannerMode=$('plannerMode').value; saveState(); renderCurrentState(); renderAutoPlan(); }
export async function onSubmitFixedSchedule(e){ e.preventDefault(); const fd=new FormData(e.currentTarget); const payload=normalizeFixedSchedule({ id:String(fd.get('editId')||'')||crypto.randomUUID(), title:String(fd.get('title')).trim(), weekday:Number(fd.get('weekday')), start:String(fd.get('start')), end:String(fd.get('end')), note:String(fd.get('note')).trim() }); if(!payload.title){ showToast('タイトルを入力してください。',{variant:'warn'}); return; } if(!isValidTimeRange(payload.start,payload.end)){ showToast('固定予定は開始時刻より後の終了時刻を設定してください。',{variant:'warn'}); return; } const editingId=String(fd.get('editId')||''); if(editingId){ const target=state.fixedSchedules.find((item)=>item.id===editingId); if(!target) return; Object.assign(target,payload); showToast('固定予定を更新しました。',{variant:'ok',duration:2200}); } else { state.fixedSchedules.push(payload); showToast('固定予定を追加しました。',{variant:'ok',duration:2200}); } saveState(); resetFixedForm(); renderAll(); }
export async function onSubmitOneOffEvent(e){ e.preventDefault(); const fd=new FormData(e.currentTarget); const editingId=String(fd.get('editId')||''); const allDay=Boolean(fd.get('allDay')); const payload=normalizeOneOffEvent({ id:editingId||crypto.randomUUID(), title:String(fd.get('title')).trim(), date:String(fd.get('date')), start:allDay?'':String(fd.get('start')||''), end:allDay?'':String(fd.get('end')||''), note:String(fd.get('note')).trim(), allDay }); if(!payload.title||!payload.date){ showToast('タイトルと日付を入力してください。',{variant:'warn'}); return; } if(!payload.allDay && payload.start && payload.end && !isValidTimeRange(payload.start,payload.end)){ showToast('単発予定は開始時刻より後の終了時刻を設定してください。',{variant:'warn'}); return; } const shouldSyncToGoogle=Boolean(fd.get('syncToGoogle')); let target=editingId?state.oneOffEvents.find((item)=>item.id===editingId):null; if(target){ Object.assign(target,payload); if(target.googleEventId){ if(hasValidGoogleToken()){ try{ await updateGoogleEventFromLocal(target); target.googleSyncStatus='synced'; } catch { target.googleSyncStatus='outdated'; } } else { target.googleSyncStatus='outdated'; } } else if(shouldSyncToGoogle && hasValidGoogleToken()){ await tryCreateGoogleForLocalEvent(target); } else if(shouldSyncToGoogle){ target.googleSyncStatus='pending'; } showToast('単発予定を更新しました。',{variant:'ok',duration:2200}); } else { target=payload; if(shouldSyncToGoogle && hasValidGoogleToken()) await tryCreateGoogleForLocalEvent(target); else if(shouldSyncToGoogle) target.googleSyncStatus='pending'; state.oneOffEvents.push(target); showToast('単発予定を追加しました。',{variant:'ok',duration:2200}); } saveState(); resetEventForm(); renderAll(); if(hasValidGoogleToken() && $('selectedDate').value===payload.date) await loadGoogleEventsForDate(payload.date,{silent:true}); }
async function tryCreateGoogleForLocalEvent(localEvent){ try{ const created=await createGoogleEventFromLocal(localEvent); localEvent.googleEventId=created.id; localEvent.googleSyncStatus='synced'; } catch { localEvent.googleSyncStatus='failed'; } }
export function onSubmitTask(e){ e.preventDefault(); const fd=new FormData(e.currentTarget); const editingId=String(fd.get('editId')||''); const payload=normalizeTask({ id:editingId||crypto.randomUUID(), title:String(fd.get('title')).trim(), category:String(fd.get('category')).trim(), deadlineDate:String(fd.get('deadlineDate')||''), deadlineTime:String(fd.get('deadlineTime')||''), estimate:String(fd.get('estimate')||''), priority:String(fd.get('priority')||'中'), importance:String(fd.get('importance')||'できれば'), note:String(fd.get('note')).trim(), status:String(fd.get('status')||'未着手'), deferUntilDate:String(fd.get('deferUntilDate')||''), protectTimeBlock:Boolean(fd.get('protectTimeBlock')) }); if(!payload.title){ showToast('タスク名を入力してください。',{variant:'warn'}); return; } if(editingId){ const target=state.tasks.find((item)=>item.id===editingId); if(!target) return; Object.assign(target,payload); showToast('タスクを更新しました。',{variant:'ok',duration:2200}); } else { state.tasks.push(payload); showToast('タスクを追加しました。',{variant:'ok',duration:2200}); } saveState(); resetTaskForm(); renderAll(); }
export function handleQuickAdd(){ const input=$('quickAddInput')?.value||''; const resultBox=$('quickAddResult'); const parsed=parseQuickAddInput(input,$('selectedDate')?.value||formatDateInput(new Date())); if(!parsed.ok){ if(resultBox) resultBox.textContent=parsed.error; showToast(parsed.error,{variant:'warn'}); return; } if(parsed.type==='task') state.tasks.push(normalizeTask({id:crypto.randomUUID(),...parsed.value})); else state.oneOffEvents.push(normalizeOneOffEvent({id:crypto.randomUUID(),googleSyncStatus:'local',...parsed.value})); saveState(); renderAll(); if(resultBox) resultBox.textContent=`追加しました: ${parsed.preview}`; if($('quickAddInput')) $('quickAddInput').value=''; showToast(`追加しました: ${parsed.preview}`,{variant:'ok',duration:2200}); }
export function resetFixedForm(){ const form=$('fixedForm'); form.reset(); form.elements.editId.value=''; $('fixedSubmitBtn').textContent='固定予定を追加'; $('fixedCancelBtn').hidden=true; setPanelOpen('fixedFormPanel',false); }
export function resetEventForm(){ const form=$('eventForm'); form.reset(); form.elements.editId.value=''; $('eventSubmitBtn').textContent='単発予定を追加'; $('eventCancelBtn').hidden=true; form.elements.date.value=$('selectedDate').value; $('syncEventToGoogle').checked=true; $('eventAllDay').checked=false; toggleEventTimeInputs(); setPanelOpen('eventFormPanel',false); }
export function resetTaskForm(){ const form=$('taskForm'); form.reset(); form.elements.editId.value=''; form.elements.priority.value='中'; form.elements.importance.value='できれば'; form.elements.status.value='未着手'; form.elements.deferUntilDate.value=''; form.elements.protectTimeBlock.checked=false; $('taskSubmitBtn').textContent='タスクを追加'; $('taskCancelBtn').hidden=true; setPanelOpen('taskFormPanel',false); }
export function toggleEventTimeInputs(){ const form=$('eventForm'); const allDay=form.elements.allDay.checked; form.elements.start.disabled=allDay; form.elements.end.disabled=allDay; if(allDay){ form.elements.start.value=''; form.elements.end.value=''; } }
export function openFixedFormForCreate(){ resetFixedForm(); const form=$('fixedForm'); focusFormPanel('fixedFormPanel',form,"input[name='title']"); }
export function openEventFormForCreate(){ resetEventForm(); const form=$('eventForm'); focusFormPanel('eventFormPanel',form,"input[name='title']"); }
export function openTaskFormForCreate(){ resetTaskForm(); const form=$('taskForm'); focusFormPanel('taskFormPanel',form,"input[name='title']"); }
export function populateFixedForm(id){ const item=state.fixedSchedules.find((entry)=>entry.id===id); if(!item) return; const form=$('fixedForm'); form.elements.editId.value=item.id; form.elements.title.value=item.title; form.elements.weekday.value=String(item.weekday); form.elements.start.value=item.start; form.elements.end.value=item.end; form.elements.note.value=item.note; $('fixedSubmitBtn').textContent='固定予定を更新'; $('fixedCancelBtn').hidden=false; focusFormPanel('fixedFormPanel',form,"input[name='title']"); }
export function duplicateFixedSchedule(id){ const item=state.fixedSchedules.find((entry)=>entry.id===id); if(!item) return; state.fixedSchedules.push({...item,id:crypto.randomUUID(),title:`${item.title} (複製)`}); saveState(); renderAll(); showToast('固定予定を複製しました。',{variant:'ok',duration:2200}); }
export async function deleteFixedSchedule(id){ const item=state.fixedSchedules.find((entry)=>entry.id===id); if(!item) return; const index=state.fixedSchedules.findIndex((entry)=>entry.id===id); state.fixedSchedules=state.fixedSchedules.filter((entry)=>entry.id!==id); saveState(); renderAll(); showToast('固定予定を削除しました。',{variant:'ok',duration:5000,actionLabel:'元に戻す',onAction:()=>{ state.fixedSchedules.splice(index,0,item); saveState(); renderAll(); showToast('固定予定を元に戻しました。',{variant:'ok',duration:1800}); }}); }
export function populateEventForm(id){ const item=state.oneOffEvents.find((entry)=>entry.id===id); if(!item) return; const form=$('eventForm'); form.elements.editId.value=item.id; form.elements.title.value=item.title; form.elements.date.value=item.date; form.elements.allDay.checked=Boolean(item.allDay); form.elements.start.value=item.start; form.elements.end.value=item.end; form.elements.note.value=item.note; $('syncEventToGoogle').checked=item.googleSyncStatus!=='local'; toggleEventTimeInputs(); $('eventSubmitBtn').textContent='単発予定を更新'; $('eventCancelBtn').hidden=false; focusFormPanel('eventFormPanel',form,"input[name='title']"); }
export function duplicateOneOffEvent(id){ const item=state.oneOffEvents.find((entry)=>entry.id===id); if(!item) return; state.oneOffEvents.push({...item,id:crypto.randomUUID(),title:`${item.title} (複製)`,googleEventId:'',googleSyncStatus:'local'}); saveState(); renderAll(); showToast('単発予定を複製しました。',{variant:'ok',duration:2200}); }
export async function deleteEvent(id){ await deleteLocalEvent(id); }
export async function syncEvent(id){ await syncLocalEventToGoogle(id); }
export async function syncUpdatedEvent(id){ await syncUpdatedLocalEventToGoogle(id); }
export function quickSetTaskStatus(id,status){ const item=state.tasks.find((entry)=>entry.id===id); if(!item) return; item.status=status; if(status==='完了') item.deferUntilDate=''; saveState(); renderAll(); showToast(`タスク状態を「${status}」に変更しました。`,{variant:'ok',duration:1800}); }
export function deferTaskToTomorrow(id){ const item=state.tasks.find((entry)=>entry.id===id); if(!item) return; const baseDate=$('selectedDate').value||formatDateInput(new Date()); item.deferUntilDate=addDays(baseDate,1); item.status=item.status==='完了'?'完了':'未着手'; saveState(); renderAll(); showToast('タスクを明日に回しました。',{variant:'ok',duration:2200}); }
export function populateTaskForm(id){ const item=state.tasks.find((entry)=>entry.id===id); if(!item) return; const form=$('taskForm'); form.elements.editId.value=item.id; form.elements.title.value=item.title; form.elements.category.value=item.category; form.elements.deadlineDate.value=item.deadlineDate; form.elements.deadlineTime.value=item.deadlineTime; form.elements.estimate.value=item.estimate; form.elements.priority.value=item.priority; form.elements.importance.value=item.importance; form.elements.status.value=item.status; form.elements.deferUntilDate.value=item.deferUntilDate; form.elements.note.value=item.note; form.elements.protectTimeBlock.checked=Boolean(item.protectTimeBlock); $('taskSubmitBtn').textContent='タスクを更新'; $('taskCancelBtn').hidden=false; focusFormPanel('taskFormPanel',form,"input[name='title']"); }
export async function deleteTask(id){ const item=state.tasks.find((entry)=>entry.id===id); if(!item) return; const index=state.tasks.findIndex((entry)=>entry.id===id); state.tasks=state.tasks.filter((entry)=>entry.id!==id); saveState(); renderAll(); showToast('タスクを削除しました。',{variant:'ok',duration:5000,actionLabel:'元に戻す',onAction:()=>{ state.tasks.splice(index,0,item); saveState(); renderAll(); showToast('タスクを元に戻しました。',{variant:'ok',duration:1800}); }}); }
export async function deleteGoogleEvent(id){ const ok=await confirmDialog({title:'Google予定を削除',message:'Googleカレンダーからこの予定を削除します。よろしいですか？',confirmText:'削除',danger:true}); if(!ok) return; await deleteGoogleEventById(id,{removeLocalMirror:true}); }
function exportData(){ const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`day-manager-backup-${formatDateInput(new Date())}.json`; document.body.appendChild(a); a.click(); a.remove(); window.setTimeout(()=>{ URL.revokeObjectURL(url); },1000); showToast('バックアップを書き出しました。',{variant:'ok',duration:2200}); }
function importData(e){ const file=e.target.files?.[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{ try{ const parsed=JSON.parse(String(reader.result)); state.fixedSchedules=(parsed.fixedSchedules||[]).map(normalizeFixedSchedule); state.oneOffEvents=(parsed.oneOffEvents||[]).map(normalizeOneOffEvent); state.tasks=(parsed.tasks||[]).map(normalizeTask); state.dayConditions=parsed.dayConditions||{}; state.settings={ focusMinutesTarget:Number(parsed.settings?.focusMinutesTarget??state.settings.focusMinutesTarget), bufferMinutes:Number(parsed.settings?.bufferMinutes??state.settings.bufferMinutes) }; state.uiState={ plannerMode:parsed.uiState?.plannerMode||'auto' }; saveState(); $('plannerMode').value=state.uiState.plannerMode; loadConditionInputsForDate($('selectedDate').value); hydrateSettingsInputs(); renderAll(); showToast('バックアップを読み込みました。',{variant:'ok',duration:2200}); } catch { showToast('JSONの読み込みに失敗しました。',{variant:'warn'}); } }; reader.readAsText(file,'utf-8'); e.target.value=''; }